# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locomoco < Formula
  desc ""
  homepage "https://github.com/faceyacc/homebrew-tools"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.9/locomoco_Darwin_x86_64.tar.gz"
      sha256 "746125d8840654786dc212ab1a7493233e89e7dd10985a002293eb3943594027"

      def install
        bin.install "locomoco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.9/locomoco_Darwin_arm64.tar.gz"
      sha256 "7f3579e97b8752775b462339ba023f5affe555347507abdb1197ae419b46769f"

      def install
        bin.install "locomoco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.9/locomoco_Linux_arm64.tar.gz"
      sha256 "ef26cc70e6231bb730bd04c2be3651e4e9d730dc4b1b200d62c5d994cafc3129"

      def install
        bin.install "locomoco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.9/locomoco_Linux_x86_64.tar.gz"
      sha256 "c31d54ab57a49c86bb42b5ebe46a1ad2fe530fb86e502edc82dba86056199e6c"

      def install
        bin.install "locomoco"
      end
    end
  end
end
