# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locomoco < Formula
  desc ""
  homepage "https://github.com/faceyacc/homebrew-tools"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.5/locomoco_Darwin_arm64.tar.gz"
      sha256 "64c4855b505ee19c0f6d1d4003527bafa3f6e32ff5bd3cf89a1eaa1e2b3e51a9"

      def install
        bin.install "locomoco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.5/locomoco_Darwin_x86_64.tar.gz"
      sha256 "5c5546ecc0380b5453c00145aa0e5fe54808216a3a9884fac410dfc476617fe8"

      def install
        bin.install "locomoco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.5/locomoco_Linux_arm64.tar.gz"
      sha256 "5de86d1a5da8f8d90ea10fbcbc018a9fcde8699423f3ae24de1ec84b3249a749"

      def install
        bin.install "locomoco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.5/locomoco_Linux_x86_64.tar.gz"
      sha256 "b729034aa5048f7636dfb48384076358fb53a7e5e535dfdb71b3f569d9bfc2df"

      def install
        bin.install "locomoco"
      end
    end
  end
end
