# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locomoco < Formula
  desc "A simple GitHub contribution and repo viewer."
  homepage "https://github.com/faceyacc/homebrew-tools"
  version "1.1.3"

  on_macos do
    url "https://github.com/faceyacc/locomoco/releases/download/v1.1.3/locomoco_1.1.3_darwin_amd64.tar.gz"
    sha256 "a475073bb0ab6b5fe892636697d56b92fd33f25fbe4a766b09d5a1807e6f6ed8"

    def install
      bin.install "locomoco"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Locomoco
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v1.1.3/locomoco_1.1.3_linux_amd64.tar.gz"
      sha256 "c0e09fc45d5509cecb496aaaf1c89594f26a2d2daec607c418f6fd8b904d7c77"

      def install
        bin.install "locomoco"
      end
    end
  end
end
