# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locomoco < Formula
  desc "A simple GitHub contribution and repo viewer."
  homepage "https://github.com/faceyacc/homebrew-tools"
  version "1.1.2"

  on_macos do
    url "https://github.com/faceyacc/locomoco/releases/download/v1.1.2/locomoco_1.1.2_darwin_amd64.tar.gz"
    sha256 "e3589d4ac16b2f0b1b12a4ef243855e91372c4cfe1a70a836aa5f4dc6c6c559a"

    def install
      bin.install "locomoco"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Locomoco
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v1.1.2/locomoco_1.1.2_linux_amd64.tar.gz"
      sha256 "6a597bc1c897890725f66736528b19fddfe2d2274348eac1e7ab75933fb4ac8a"

      def install
        bin.install "locomoco"
      end
    end
  end
end
