# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locomoco < Formula
  desc "A simple GitHub contribution and repo viewer."
  homepage "https://github.com/faceyacc/homebrew-tools"
  version "0.0.1"

  on_macos do
    url "https://github.com/faceyacc/locomoco/releases/download/v0.0.1/locomoco_0.0.1_darwin_amd64.tar.gz"
    sha256 "02da31008e747c5d69724db58e6dd30595d4f5cb795cf5316b74b27a489de226"

    def install
      bin.install "locomoco"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Locomoco
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/faceyacc/locomoco/releases/download/v0.0.1/locomoco_0.0.1_linux_amd64.tar.gz"
      sha256 "a2f970a1875f57ae6d043159571d3729c1950fd01f2d9822f395c03c074e1e90"

      def install
        bin.install "locomoco"
      end
    end
  end
end
